[directories]
spherical_integrals = "sample_points/data"
sdpb_input = "problems"
sdpb_output = "output"
sdpb_binaries = "sdpb_binaries"
checkpoints = "problems"
mathematica = "mathematica"

[grid]
gridPoints = 400
maxN = 16

[[grid.spins]]
minL = 0
maxL = 50
partition_by = 5

[[problem]]
N = 3
ansatz_size = 10
spins = [10, 15, 20, 25, 30]

[[problem]]
N = 3
ansatz_size = 12
spins = [10, 15, 20]

[mathematica]
accuracy_goal = 20
precision_goal = 150

[physics]
z0 = 0
m = 0
problem_type = "A1Bound_A0=1"

[sdpb]
precision = 1024 # in binary digits
duality_gap_threshold = 1e-7
nodes_per_job = 2
processes_per_node = 28
max_iterations = 700
max_complementarity = 1e60

[debug]
dry_run = true # don't run the jobs
use_debug_partition = true